#!/bin/bash

echo "to the new home"
SCRIPT_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

## create symlink
ln -sf "$SCRIPT_DIR/bin" "$HOME/bin"
ln -sf "$SCRIPT_DIR/.inputrc" "$HOME/.inputrc"
ln -sf "$SCRIPT_DIR/.vimrc" "$HOME/.vimrc"
ln -sf "$SCRIPT_DIR/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$SCRIPT_DIR/.mybashrc" "$HOME/.mybashrc"
ln -sf "$SCRIPT_DIR/.gitconfig" "$HOME/.gitconfig"
echo '. "$HOME/.mybashrc"' >> "$HOME/.bashrc"

#zsh
sh $SCRIPT_DIR/scripts/install_zsh
#[ -f "$HOME/.zshrc" ] && echo '. "$HOME/.mybashrc"\n' >> "$HOME/.zshrc"
[ -f "$HOME/.zshrc" ] && echo '[[ -f "$HOME/.mybashrc" ]] && . "$HOME/.mybashrc"' >> "$HOME/.zshrc"

#cargo
sh $SCRIPT_DIR/scripts/install_cargo

#golang
sh $SCRIPT_DIR/scripts/install_golang


mkdir -p "$HOME/.config" 2>&1 >/dev/null
cp -rfT "$SCRIPT_DIR/.local" "$HOME/.local"

## i3 & i3block
ln -sf "$SCRIPT_DIR/.config/i3" "$HOME/.config/i3"
ln -sf "$SCRIPT_DIR/.config/i3blocks" "$HOME/.config/i3blocks"

## alacrity
ln -sf "$SCRIPT_DIR/.config/alacritty" "$HOME/.config/alacritty"

## volumeicon
ln -sf "$SCRIPT_DIR/.config/volumeicon" "$HOME/.config/volumeicon"

## konsole
ln -sf "$SCRIPT_DIR/.config/konsolerc" "$HOME/.config/konsolerc"

## Xresources
ln -sf "$SCRIPT_DIR/.Xresources" "$HOME/.Xresources"
ln -sf "$SCRIPT_DIR/.Xresources.d" "$HOME/.Xresources.d"

## ~/.config/autostart/
ln -sf "$SCRIPT_DIR/.config/autostart" "$HOME/.config/autostart"

## ~/.config/nvim/
ln -sf "$SCRIPT_DIR/.config/nvim" "$HOME/.config/nvim"

echo "***END***"
