#!/bin/bash

# kiem tra zsh
if ! command -v go &>/dev/null; then
  wget https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
  sudo rm -rf /usr/local/go
  sudo tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
  rm go1.22.5.linux-amd64.tar.gz
fi

echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.zshrc
